export const requests = [
  {
    id: 1,
    title: "درخواست ثبت پایانه جدید از psp پرداخت نوین",
    description: "a",
    code: 0,
    merchant: "",
    nationalCode: "",
    merchantNumber: "",
    company: "",
    terminalCount: 0,
  },
  {
    id: 2,
    title: "درخواست قطع پایانه از psp سداد",
    description: "b",
    code: 0,
    merchant: "",
    nationalCode: "",
    merchantNumber: "",
    company: "",
    terminalCount: 0,
  },
  {
    id: 3,
    title: "درخواست تغییر کد صنف از psp به پرداخت",
    description: "c",
    code: 0,
    merchant: "",
    nationalCode: "",
    merchantNumber: "",
    company: "",
    terminalCount: 0,
  },
  {
    id: 4,
    title: "درخواست تغییر شبا از پرداختیار x",
    description: "d",
    code: 0,
    merchant: "",
    nationalCode: "",
    merchantNumber: "",
    company: "",
    terminalCount: 0,
  },
];
